#:schema node_modules/wrangler/config-schema.json
name = "genurl"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "urlgen", id = "0b1bd153b3974e8191fbe6f646517e30" }
]
